### PR TITLE
Fixed python3 issues

### PR DESCRIPTION
**Pull request by shantanu69**
Actullay refactored the code so that it can run both on python3 and python2
The changes include:
*  print_function
*  use of range
*  wrapping `map` function with `list`
*  some flake8 styling issues

### CODE REVIEW

**Comment by facebook-github-bot-5** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by shantanu69** [comment]
A followup of #74

**Comment by modocache** [comment]
Thanks,  @shantanu69! Very much appreciated. ❤️

**Comment by shantanu69** [comment]
You are welcome :smile:

**Pull request merged**
